package com.mivim.data.model;

import java.util.Date;

public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.id
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.userId
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.addressLine1
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    private String addressLine1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.addressLine2
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    private String addressLine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.city
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.state
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.pincode
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    private String pincode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.updatedDate
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.status
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.id
     *
     * @return the value of address.id
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.id
     *
     * @param id the value for address.id
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.userId
     *
     * @return the value of address.userId
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.userId
     *
     * @param userId the value for address.userId
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.addressLine1
     *
     * @return the value of address.addressLine1
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    public String getAddressLine1() {
        return addressLine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.addressLine1
     *
     * @param addressLine1 the value for address.addressLine1
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1 == null ? null : addressLine1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.addressLine2
     *
     * @return the value of address.addressLine2
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    public String getAddressLine2() {
        return addressLine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.addressLine2
     *
     * @param addressLine2 the value for address.addressLine2
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2 == null ? null : addressLine2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.city
     *
     * @return the value of address.city
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.city
     *
     * @param city the value for address.city
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.state
     *
     * @return the value of address.state
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.state
     *
     * @param state the value for address.state
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.pincode
     *
     * @return the value of address.pincode
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    public String getPincode() {
        return pincode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.pincode
     *
     * @param pincode the value for address.pincode
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    public void setPincode(String pincode) {
        this.pincode = pincode == null ? null : pincode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.updatedDate
     *
     * @return the value of address.updatedDate
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.updatedDate
     *
     * @param updatedDate the value for address.updatedDate
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.status
     *
     * @return the value of address.status
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.status
     *
     * @param status the value for address.status
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}