package com.mivim.data.model;

public class CityStateList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_state_list.city_id
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    private String city_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_state_list.city_name
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    private String city_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_state_list.city_par_id
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    private String city_par_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_state_list.city_id
     *
     * @return the value of city_state_list.city_id
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    public String getCity_id() {
        return city_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_state_list.city_id
     *
     * @param city_id the value for city_state_list.city_id
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    public void setCity_id(String city_id) {
        this.city_id = city_id == null ? null : city_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_state_list.city_name
     *
     * @return the value of city_state_list.city_name
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    public String getCity_name() {
        return city_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_state_list.city_name
     *
     * @param city_name the value for city_state_list.city_name
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    public void setCity_name(String city_name) {
        this.city_name = city_name == null ? null : city_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_state_list.city_par_id
     *
     * @return the value of city_state_list.city_par_id
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    public String getCity_par_id() {
        return city_par_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_state_list.city_par_id
     *
     * @param city_par_id the value for city_state_list.city_par_id
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    public void setCity_par_id(String city_par_id) {
        this.city_par_id = city_par_id == null ? null : city_par_id.trim();
    }
}