package com.mivim.data.model;

public class Itemcategory extends ItemcategoryKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemcategory.subCategoryId
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    private String subCategoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemcategory.subCategoryId
     *
     * @return the value of itemcategory.subCategoryId
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    public String getSubCategoryId() {
        return subCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemcategory.subCategoryId
     *
     * @param subCategoryId the value for itemcategory.subCategoryId
     *
     * @mbggenerated Wed Jul 19 13:41:14 IST 2017
     */
    public void setSubCategoryId(String subCategoryId) {
        this.subCategoryId = subCategoryId == null ? null : subCategoryId.trim();
    }
}