package com.mivim.data.dao;

import com.mivim.data.model.CityStateList;
import com.mivim.data.model.CityStateListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CityStateListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_state_list
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    long countByExample(CityStateListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_state_list
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    int deleteByExample(CityStateListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_state_list
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    int deleteByPrimaryKey(String city_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_state_list
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    int insert(CityStateList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_state_list
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    int insertSelective(CityStateList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_state_list
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    List<CityStateList> selectByExample(CityStateListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_state_list
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    CityStateList selectByPrimaryKey(String city_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_state_list
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    int updateByExampleSelective(@Param("record") CityStateList record, @Param("example") CityStateListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_state_list
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    int updateByExample(@Param("record") CityStateList record, @Param("example") CityStateListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_state_list
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    int updateByPrimaryKeySelective(CityStateList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_state_list
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    int updateByPrimaryKey(CityStateList record);
}