package com.mivim.data.dao;

import com.mivim.data.model.UserroleExample;
import com.mivim.data.model.UserroleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    long countByExample(UserroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    int deleteByExample(UserroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    int deleteByPrimaryKey(UserroleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    int insert(UserroleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    int insertSelective(UserroleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    List<UserroleKey> selectByExample(UserroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    int updateByExampleSelective(@Param("record") UserroleKey record, @Param("example") UserroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbg.generated Wed Jul 19 11:59:46 IST 2017
     */
    int updateByExample(@Param("record") UserroleKey record, @Param("example") UserroleExample example);
}